name: SkriptDocsGenerator
description: Generate documentation for your Skript addon !
author: Skylyxx
website: https://github.com/Skylyxx/SkriptDocsGenerator
main: fr.skylyxx.docsgenerator.SkriptDocsGenerator
version: @version@
api-version: @apiVersion@
softdepend: [Skript]
commands:
  skriptdocsgenerator:
    description: Command to generate docs
    permission: skriptdocsgenerator.use
    aliases: ['docs', 'skriptdocs', 'docsgenerator']