name: build
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
      - name: Set up JDK 8
        uses: actions/setup-java@v1.4.3
        with:
          java-version: 1.8
          java-package: jdk
      - name: Make gradlew executable
        run: chmod +x ./gradlew
      - name: Build with Gradle
        run: ./gradlew clean githubRelease
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
      - name: Set up JDK 8
        uses: actions/setup-java@v1.4.3
        with:
          java-version: 1.8
          java-package: jdk
      - name: Make gradlew executable
        run: chmod +x ./gradlew
      - name: Build with Gradle
        run: ./gradlew clean githubRelease
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: SkriptDocsGenerator-Github
          path: build/libs/**